// Re-export all types from the main source — single source of truth.
export type {
  WidgetProps,
  Step,
  OrderState,
  DepositOption,
  DepositOptionsResponse,
  QuoteResponse,
  AmountLimitsResponse,
  TransferQuoteSnapshot,
  RequirementsField,
  RequirementsGroup,
  AccountType,
  RequirementsResponse,
  RecipientResponse,
  CreateRecipientPayload,
  CreateTransferPayload,
  TransferResponse,
  RecipientSnapshot,
  TransferRecord,
  TransferStatusResponse,
  OtpSendResponse,
  OtpVerifyResponse,
} from '../src/types'
